# -*- coding: utf-8 -*-
# 应用配置
app:
  name: "zadmin"
  version: "1.0"
  host: "0.0.0.0"
  port: 8000
  debug: true
  secret_key: "your-secret-key-here"
  allowed_origins:
    - "*"


# 数据库配置
database:
  url: "mysql+pymysql://root:123456@127.0.0.1:3306/zadmin"
  async_url: "mysql+asyncmy://root:123456@127.0.0.1:3306/zadmin"
  pool_size: 20
  echo_sql: false  # 是否打印SQL日志

# Redis配置
redis:
  host: "localhost"
  port: 6379
  password: ""  # 若无密码则留空
  db: 0

# 日志配置
logging:
  level: "INFO"
  log_path: "logs/app.log"
  error_path: "logs/error.log"
  rotate_size: 10  # 日志文件轮转大小 单位M
  back_files: 5 # 多保留n个备份

