# -*- coding: utf-8 -*-
# 应用配置
app:
  name: "zadmin"
  version: "1.0"
  host: "0.0.0.0"
  port: 8000
  debug: true
  secret_key: "your-secret-key-here"
  allowed_origins:
    - "*"


# 数据库配置
database:
  url: "mysql+pymysql://root:123456@127.0.0.1:3306/zadmin"
  async_url: "mysql+asyncmy://root:123456@127.0.0.1:3306/zadmin"
  pool_size: 20
  echo_sql: false  # 是否打印SQL日志

# Redis配置
redis:
  url: "redis://:123456@127.0.0.1:6379/0"

cors:
  # 只允许访问的域名列表，* 代表所有
  allow_origins: ['*']
  # 是否支持携带 cookie
  allow_credentials: true
  # 设置允许跨域的http方法，比如 get、post、put等。
  allow_methods: ["*"]
  # 允许携带的headers，可以用来鉴别来源等作用。
  allow_headers: ["*"]

jwt:
  secret_key: vgb0tnl9d58+6n-6h-ea&u^1#s0ccp!794=kbvqacjq75vzps$
  expires_in: 7200

# 日志配置
logging:
  level: "INFO"
  log_path: "logs/app.log"
  error_path: "logs/error.log"
  rotate_size: 10  # 日志文件轮转大小 单位M
  back_files: 5 # 多保留n个备份

